name: Commit generated file to another repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: yochem/yochem.github.io
          token: ${{ secrets.PAT }}
          path: website

      - name: Generate file
        run: echo "test" > website/test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          path: website
          branch: new-calendar
          title: 'Add generated file'
          body: 'This PR adds the generated file.'

